info: {}
paths:
  /group/:
    post:
      operationId: groupPost
      responses:
        "200":
          $ref: '#/responses/handleGroupPost'
      summary: Creates a new group.
      tags:
      - group-tag
swagger: "2.0"
